### PR TITLE
fix(l10n): Fix "created by" message

### LINKED ISSUE #9: l10n: Strings need adaption before translation can start
Hello,

I exported po file from Tx and check all strings.

Here are my findings:

```
#. TRANSLATORS onents/PexipCall.vue:41
#: /app/main/specialVueFakeDummyForL10nScript.js:234
msgid "Pexip meeting created by"
msgstr ""

-> Will a person's name be added to this string? If so, the person's name should be included in the string using a placeholder.
---

#: /app/main/specialVueFakeDummyForL10nScript.js:313
msgid "Between 4 and 20 digits optionally endind with one or more #"
msgstr ""

-> Please check sentence. Endind -> ending? Or "...optionally followed by one or more #""
```

Please adapt source strings.
After you are done the resource will be enabled at Tx and translation will start.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #9

### CODE REVIEW

File: src/components/PexipCall.vue [hunk 1]
```diff
@@ -173,10 +169,14 @@ export default {
...
-			return getCurrentUser()?.uid === this.call.user_id
-				? t('integration_pexip', 'You')
-				: this.call.user_name
+		createdByLabel() {
+			if (getCurrentUser()?.uid === this.call.user_id) {
+				return t('integration_pexip', 'Pexip meeting created by you')
+			}
+
+			return t('integration_pexip', 'Pexip meeting created by {displayname}', {
+				displayname: this.call.user_name
```
Comment (julien-nc) [inline src/components/PexipCall.vue]:
```suggestion
				displayname: this.call.user_name,
```

File: src/components/PexipCall.vue
Comment (julien-nc) [inline src/components/PexipCall.vue]: Not used anymore.

Comment (julien-nc) [inline src/components/PexipCall.vue]: Not used anymore.

**Review by julien-nc — CHANGES_REQUESTED** [review]

**Review by julien-nc — APPROVED** [review]
